language: generic

dist: trusty
sudo: required

services:
  - docker

before_install:
  - echo '{"ipv6":true,"fixed-cidr-v6":"2001:db8:1::/64"}' | sudo tee /etc/docker/daemon.json
  - sudo service docker restart

install:
  - docker build -t nginx .

script:
  - sh runTests.sh
