name: CI

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - "*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create global $VERSION
        run: |
          # Strip git ref prefix from version
          ### example: github.ref=refs/tags/1.2.3 -> VERSION=1.2.3
          ### example: github.ref=refs/heads/master -> VERSION=master
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [ "$VERSION" == "master" ] && VERSION=latest
          [ "$VERSION" == "merge" ] && VERSION=dev

          echo Version tag that is being used $VERSION
          echo VERSION=$(echo "$VERSION") >> $GITHUB_ENV

      - name: Enable ipv6 for docker
        if: github.event_name == 'pull_request'
        run: |
          echo '{"ipv6":true,"fixed-cidr-v6":"2001:db8:1::/64"}' | sudo tee /etc/docker/daemon.json
          sudo service docker restart

      - uses: whoan/docker-build-with-cache-action@v5
        with:
          username: yoohahn
          password: "${{ secrets.DOCKER_HUB_TOKEN }}"
          image_name: nginx
          dockerfile: ./  
          image_tag: ${{ env.VERSION }}
          push_image_and_stages: on:push

      - name: Run 'runTests.sh'
        if: github.event_name == 'pull_request'
        run: sh runTests.sh
